DonorCentar/DonorCentar/Models/Administrator.cs
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel.DataAnnotations;

namespace DonorCentar.Models
{
    public class Administrator
    {
        public int Id { get; set; }
        public Korisnik Korisnik { get; set; }
        public int KorisnikId { get; set; }
    }
}

DonorCentar/DonorCentar/Models/Donor.cs
using System;
using System.Collections.Generic;
using System.Text;


namespace DonorCentar.Models
{
    public class Donor
    {
        public int Id { get; set; }
        public Korisnik Korisnik { get; set; }
        public int KorisnikId { get; set; }
        public DateTime DatumRegistracije { get; set; }
    }
}

DonorCentar/DonorCentar/Models/Partner.cs
using System;
using System.Collections.Generic;
using System.Text;

namespace DonorCentar.Models
{
    public class Partner
    {
        public int Id { get; set; }
        public Korisnik Korisnik { get; set; }
        public int KorisnikId { get; set; }
        public DateTime DatumRegistracije { get; set; }
    }
}

DonorCentar/DonorCentar/Models/Primalac.cs
using System;
using System.Collections.Generic;
using System.Text;


namespace DonorCentar.Models
{
    public class Primalac
    {
        public int Id { get; set; }
        public Korisnik Korisnik { get; set; }
        public int KorisnikId { get; set; }
        public DateTime DatumRegistracije { get; set; }
        public bool Verifikovan { get; set; }
    }
}

DonorCentar/DonorCentar/Controllers/DonorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DonorCentar.Helper;
using DonorCentar.Hubs;
using DonorCentar.Models;
using DonorCentar.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;

namespace DonorCentar.Controllers
{
    public class DonorController : Controller
    {
        private BazaPodataka db;
        private IHubContext<NotificationHub> _hubContext;
        public DonorController(IHubContext<NotificationHub> hubContext, BazaPodataka _db)
        {
            _hubContext = hubContext;
            db = _db;
        }
        public IActionResult Index()
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 1)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            int donorId = db.Donor.Where(d => d.KorisnikId == k.Id).FirstOrDefault().Id;

            var korisnikViewModel = new KorisnikVM
            {
                Id = donorId,
                Naziv = k.LicniPodaci.Naziv,
                TipKorisnika = k.TipKorisnika.Tip,
                Adresa = k.LicniPodaci.Adresa,
                BrojTelefona = k.LicniPodaci.BrojTelefona,
                Email = k.LicniPodaci.Email,
                Grad = k.Grad.Naziv,
                PozitivniDojmovi = db.DojamKorisnik.Where(d => d.KorisnikId == k.Id).Count(d => d.DojamId == 1),
                NeutralniDojmovi = db.DojamKorisnik.Where(d => d.KorisnikId == k.Id).Count(d => d.DojamId == 2),
                NegativniDojmovi = db.DojamKorisnik.Where(d => d.KorisnikId == k.Id).Count(d => d.DojamId == 3)
            };

            PostaviViewBag(k.Id, "Index");
            return View(korisnikViewModel);
        }

        public ActionResult Obavijesti()
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 1)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            ObavijestiVM model = new ObavijestiVM
            {
                rows = db.Obavijest.Where(d => d.ZaKorisnikId == k.Id).Select(o => new ObavijestiVM.Row
                {
                    ZaKorisnikId = o.ZaKorisnikId,
                    ObavijestId = o.ObavijestId,
                    Naziv = o.OdKorisnik.LicniPodaci.Naziv,
                    Obavijest = o.TipObavijesti.Obavijest,
                    Vrijeme = o.Vrijeme,
                    OdKorisnikId = o.OdKorisnikId,
                    TipKorisnikaId = o.TipKorisnikaId,
                    TipObavijestiId = o.TipObavijestiId
                }).ToList()
            };

            PostaviViewBag(k.Id, "Obavijesti");
            return View(model);
        }
        public ActionResult DodajDonaciju()
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 1)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }
            /*PRILIKOM DODAVANJA DONACIJE -> DonorID = KorisnikID od donora*/

            PostaviViewBag(k.Id, "DodajDonaciju");
            return View();
        }

        public ActionResult PregledPotreba()
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 1)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            DonorPregledPotrebaVM model = new DonorPregledPotrebaVM
            {
                rows = db.Donacija.Where(d => d.StatusId == 2).Select(d => new DonorPregledPotrebaVM.Row
                {
                    DonacijaId = d.DonacijaId,
                    LicniPodaciNaziv = d.Primalac.LicniPodaci.Naziv,
                    PrimalacId = (int)d.PrimalacId,
                    StatusId = d.StatusId,
                    StatusOpis = d.Status.Opis,
                    TipDonacije = d.TipDonacije.Tip
                }).ToList()
            };

            PostaviViewBag(k.Id, "PregledPotreba");
            return View(model);
        }

        public ActionResult DonacijeBezTransporta()
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 1)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            PostaviViewBag(k.Id, "DonacijeBezTransporta");
            return View();
        }

        public ActionResult HistorijaDonacija()
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 1)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            /*Ukoliko Donor nije ostavio dojam primaocu za zavrsenu donaciju,
              treba da postoji button "Ostavi dojam" */

            PostaviViewBag(k.Id, "HistorijaDonacija");
            return View();
        }

        public ActionResult OstaliKorisnici()
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 1)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            PostaviViewBag(k.Id, "OstaliKorisnici");
            return View();
        }

        public ActionResult DetaljiDonacije(int donacijaId, int akcija)
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 1)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            Donacija donacija = db.Donacija.Where(d => d.DonacijaId == donacijaId)
                .Include(d => d.Status)
                .Include(d => d.Primalac)
                .Include(d => d.Primalac.LicniPodaci)
                .Include(d => d.Primalac.Grad)
                .Include(d => d.TipDonacije)
                .FirstOrDefault();

            DonorDetaljiDonacijeVM model = new DonorDetaljiDonacijeVM
            {
                DonacijaId = donacijaId,
                JedinicaMjere = (JedinicaMjere)donacija.JedinicaMjere,
                Kolicina = donacija.Kolicina,
                Opis = donacija.Opis,
                StatusOpis = donacija.Status.Opis,
                TipDonacije = donacija.TipDonacije.Tip
            };

            if (donacija.Primalac != null)
            {
                model.PrimalacAdresa = donacija.Primalac.LicniPodaci.Adresa;
                model.PrimalacGrad = donacija.Primalac.Grad.Naziv;
                model.PrimalacLicniPodaciNaziv = donacija.Primalac.LicniPodaci.Naziv;
            } else
            {
                model.PrimalacAdresa = "Donacija je bez primaoca";
                model.PrimalacGrad = "";
                model.PrimalacLicniPodaciNaziv = "Donacija je bez primaoca";
            }

            if (akcija == 1)
            {
                PostaviViewBag(k.Id, "MojeAktivneDonacije");
            }
            else
            {
                PostaviViewBag(k.Id, "PregledPotreba");
            }

            ViewBag.Akcija = akcija;
            return View(model);
        }

        public ActionResult PrekiniDonaciju(int donacijaId)
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 1)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            Donacija d = db.Donacija.Find(donacijaId);

            Obavijest o = new Obavijest
            {
                DonacijaId = donacijaId,
                OdKorisnikId = k.Id,
                TipKorisnikaId = 2,
                TipObavijestiId = 9,
                Vrijeme = DateTime.Now,
                ZaKorisnikId = (int)d.PrimalacId
            };

            d.PrimalacId = null;
            d.TransportId = null;
            d.StatusId = 1;
            db.Obavijest.Add(o);
            db.SaveChanges();

            _hubContext.Clients.All.SendAsync("ReceiveNotification", o.ZaKorisnikId);

            return RedirectToAction("MojeAktivneDonacije");
        }

        public ActionResult OdbijZahtjev(int donacijaId)
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 1)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            Donacija d = db.Donacija.Find(donacijaId);

            Obavijest o = new Obavijest
            {
                DonacijaId = donacijaId,
                OdKorisnikId = k.Id,
                TipKorisnikaId = 2,
                TipObavijestiId = 7,
                Vrijeme = DateTime.Now,
                ZaKorisnikId = (int)d.PrimalacId
            };

            d.PrimalacId = null;
            d.TransportId = null;
            d.StatusId = 1;
            db.Obavijest.Add(o);
            db.SaveChanges();

            _hubContext.Clients.All.SendAsync("ReceiveNotification", o.ZaKorisnikId);

            return RedirectToAction("MojeAktivneDonacije");
        }

        public ActionResult MojeAktivneDonacije()
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 1)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

DonorCentar/DonorCentar/Controllers/PartnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DonorCentar.Helper;
using DonorCentar.Hubs;
using DonorCentar.Models;
using DonorCentar.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;

namespace DonorCentar.Controllers
{
    public class PartnerController : Controller
    {
        private BazaPodataka db;
        private IHubContext<NotificationHub> _hubContext;

        public PartnerController(IHubContext<NotificationHub> hubContext, BazaPodataka _db)
        {
            db = _db;
            _hubContext = hubContext;
        }

        public IActionResult Index()
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 3)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            int partnerId = db.Partner.Where(d => d.KorisnikId == k.Id).FirstOrDefault().Id;

            var korisnikViewModel = new KorisnikVM
            {
                Id = partnerId,
                Naziv = k.LicniPodaci.Naziv,
                TipKorisnika = k.TipKorisnika.Tip,
                Adresa = k.LicniPodaci.Adresa,
                BrojTelefona = k.LicniPodaci.BrojTelefona,
                Email = k.LicniPodaci.Email,
                Grad = k.Grad.Naziv,
                PozitivniDojmovi = db.DojamKorisnik.Where(d => d.KorisnikId == k.Id).Count(d => d.DojamId == 1),
                NeutralniDojmovi = db.DojamKorisnik.Where(d => d.KorisnikId == k.Id).Count(d => d.DojamId == 2),
                NegativniDojmovi = db.DojamKorisnik.Where(d => d.KorisnikId == k.Id).Count(d => d.DojamId == 3)
            };

            PostaviViewBag(k.Id, "Index");
            return View(korisnikViewModel);
        }

        public ActionResult Obavijesti()
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 3)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            PostaviViewBag(k.Id, "Obavijesti");
            return View();
        }
        public ActionResult DonacijeBezTransporta()
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 3)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            PostaviViewBag(k.Id, "DonacijeBezTransporta");
            return View();
        }
        public ActionResult HistorijaDonacija()
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 3)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            PostaviViewBag(k.Id, "HistorijaDonacija");
            return View();
        }
        public ActionResult OstaliKorisnici()
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 3)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            PostaviViewBag(k.Id, "OstaliKorisnici");
            return View();
        }

        public void PostaviViewBag(int KorisnikId, string active)
        {
            ViewBag.brojObavijesti = db.Obavijest.Where(o => o.ZaKorisnikId == KorisnikId).Count();
            ViewBag.Active = active;
        }
    }
}

DonorCentar/DonorCentar/Views/Shared/_Donor.cshtml
@using DonorCentar.Helper;

@{
    Layout = null;
    //  BazaPodataka db = new BazaPodataka();
    int KorisnikId = Context.GetLogiraniKorisnik().Id;
    int brojObavijesti = ViewBag.brojObavijesti;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DonorCentar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/lux.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="icon" href="~/img/logo.png" />
    <script src="~/js/SignalR/dist/browser/signalr.min.js"></script>

</head>
<body>
    <div id="main">
        <div id="left">
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
                <div class="container">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="mb-3">
                            <img src="~/img/logo.png" alt="" />
                        </li>
                        <li>
                            @if (ViewBag.Active == "Index")
                            {
                                <a class="nav-link text-light top-b activee" asp-controller="Donor" asp-action="Index">Profil</a>
                            }
                            else
                            {
                                <a class="nav-link text-light top-b" asp-controller="Donor" asp-action="Index">Profil</a>
                            }
                        </li>
                        <li>
                            @if (ViewBag.Active == "Obavijesti")
                            {
                                <a class="nav-link text-light activee" asp-controller="Donor" asp-action="Obavijesti">
                                    Obavijesti
                                    <span id="brojObavijestiDonor" class="badge badge-primary badge-pill">@brojObavijesti</span>
                                </a>
                            }
                            else
                            {
                                <a class="nav-link text-light" asp-controller="Donor" asp-action="Obavijesti">
                                    Obavijesti
                                    <span id="brojObavijestiDonor" class="badge badge-primary badge-pill">@brojObavijesti</span>
                                </a>
                            }
                        </li>
                        <li>
                            @if (ViewBag.Active == "DodajDonaciju")
                            {
                                <a class="nav-link text-light activee" asp-controller="Donor" asp-action="DodajDonaciju">Dodaj donaciju</a>
                            }
                            else
                            {
                                <a class="nav-link text-light" asp-controller="Donor" asp-action="DodajDonaciju">Dodaj donaciju</a>
                            }
                        </li>
                        <li>
                            @if (ViewBag.Active == "MojeAktivneDonacije")
                            {
                                <a class="nav-link text-light activee" asp-controller="Donor" asp-action="MojeAktivneDonacije">Moje aktivne donacije</a>
                            }
                            else
                            {
                                <a class="nav-link text-light" asp-controller="Donor" asp-action="MojeAktivneDonacije">Moje aktivne donacije</a>
                            }
                        </li>
                        <li>
                            @if (ViewBag.Active == "PregledPotreba")
                            {
                                <a class="nav-link text-light activee" asp-controller="Donor" asp-action="PregledPotreba">Pregled potreba</a>
                            }
                            else
                            {
                                <a class="nav-link text-light" asp-controller="Donor" asp-action="PregledPotreba">Pregled potreba</a>
                            }
                        </li>
                        <li>
                            @if (ViewBag.Active == "DonacijeBezTransporta")
                            {
                                <a class="nav-link text-light activee" asp-controller="Donor" asp-action="DonacijeBezTransporta">Donacije bez transporta</a>
                            }
                            else
                            {
                                <a class="nav-link text-light" asp-controller="Donor" asp-action="DonacijeBezTransporta">Donacije bez transporta</a>
                            }
                        </li>
                        <li>
                            @if (ViewBag.Active == "HistorijaDonacija")
                            {
                                <a class="nav-link text-light activee" asp-controller="Donor" asp-action="HistorijaDonacija">Historije donacija</a>
                            }
                            else
                            {
                                <a class="nav-link text-light" asp-controller="Donor" asp-action="HistorijaDonacija">Historije donacija</a>
                            }
                        </li>
                        <li>
                            @if (ViewBag.Active == "OstaliKorisnici")
                            {
                                <a class="nav-link text-light activee" asp-controller="Donor" asp-action="OstaliKorisnici">Ostali korisnici</a>
                            }
                            else
                            {
                                <a class="nav-link text-light" asp-controller="Donor" asp-action="OstaliKorisnici">Ostali korisnici</a>
                            }
                        </li>
                        <li>
                            <a class="nav-link btn btn-secondary text-dark mt-5" asp-controller="Home" asp-action="Index">Odjavi se</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <div id="right">
            <div class="container">
                <main role="main">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>


    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    <script>
        function updateNotificationCount(id) {
            if (@KorisnikId == id) {
                var count = parseInt($("#brojObavijestiDonor").text(), 10);
                count = count + 1;
                $("#brojObavijestiDonor").text(count);
            }
        }

        $(function () {
            var notificationHub = new signalR.HubConnectionBuilder().withUrl("/notificationHub").build();

            notificationHub.start().then(function () {
                console.log("Notification hub started");
            });

            notificationHub.on("ReceiveNotification", function (id) {
                updateNotificationCount(id);
            });
        });
    </script>
</body>
</html>

DonorCentar/DonorCentar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/lux.css" />
    <link rel="stylesheet" href="~/css/style.css" />



    <link rel="icon" href="~/img/logo.png" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <img src="~/img/logo.png" class="mr-3 navbar-img" />
                <a class="navbar-brand" id="donor-title" asp-area="" asp-controller="Home" asp-action="Index">DonorCentar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="ONama">O nama</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Registracija">Registracija</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>


    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

DonorCentar/DonorCentar/Views/Shared/_Partner.cshtml
@using DonorCentar.Helper;
@{
    Layout = null;
    int KorisnikId = Context.GetLogiraniKorisnik().Id;
    int brojObavijesti = ViewBag.brojObavijesti;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />

    <title>Partner</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/lux.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="icon" href="~/img/logo.png" />
    <script src="~/js/SignalR/dist/browser/signalr.min.js"></script>

</head>
<body>
    <div id="main">
        <div id="left">
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
                <div class="container">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="mb-3">
                            <img src="~/img/logo.png" alt="" />
                        </li>
                        <li>
                            @if (ViewBag.Active == "Index")
                            {
                                <a class="nav-link text-light top-b activee" asp-controller="Partner" asp-action="Index">Profil</a>
                            }
                            else
                            {
                                <a class="nav-link text-light top-b" asp-controller="Partner" asp-action="Index">Profil</a>
                            }
                        </li>
                        <li>
                            @if (ViewBag.Active == "Obavijesti")
                            {
                                <a class="nav-link text-light activee" asp-controller="Partner" asp-action="Obavijesti">Obavijesti</a>
                            }
                            else
                            {
                                <a class="nav-link text-light" asp-controller="Partner" asp-action="Obavijesti">Obavijesti</a>
                            }
                        </li>
                        <li>
                            @if (ViewBag.Active == "DonacijeBezTransporta")
                            {
                                <a class="nav-link text-light activee" asp-controller="Partner" asp-action="DonacijeBezTransporta">Donacije bez transporta</a>
                            }
                            else
                            {
                                <a class="nav-link text-light" asp-controller="Partner" asp-action="DonacijeBezTransporta">Donacije bez transporta</a>
                            }
                        </li>
                        <li>
                            @if (ViewBag.Active == "HistorijaDonacija")
                            {
                                <a class="nav-link text-light activee" asp-controller="Partner" asp-action="HistorijaDonacija">Historije donacija</a>
                            }
                            else
                            {
                                <a class="nav-link text-light" asp-controller="Partner" asp-action="HistorijaDonacija">Historije donacija</a>
                            }
                        </li>
                        <li>
                            @if (ViewBag.Active == "OstaliKorisnici")
                            {
                                <a class="nav-link text-light activee" asp-controller="Partner" asp-action="OstaliKorisnici">Ostali korisnici</a>
                            }
                            else
                            {
                                <a class="nav-link text-light" asp-controller="Partner" asp-action="OstaliKorisnici">Ostali korisnici</a>
                            }
                        </li>
                        <li>
                            <a class="nav-link btn btn-secondary text-dark mt-5" asp-area="" asp-controller="Home" asp-action="Index">Odjavi se</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <div id="right">
            <div class="container">
                <main role="main">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>


    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <script>
             function updateNotificationCount(id) {
            if (@KorisnikId == id) {
                var count = parseInt($("#brojObavijestiPartner").text(), 10);
                count = count + 1;
                $("#brojObavijestiPartner").text(count);
            }
        }

        $(function () {
            var notificationHub = new signalR.HubConnectionBuilder().withUrl("/notificationHub").build();

            notificationHub.start().then(function () {
                console.log("Notification hub started");
            });

            notificationHub.on("ReceiveNotification", function (id) {
                updateNotificationCount(id);
            });
        });
    </script>
</body>
</html>