DonorCentar/DonorCentar/Models/Primalac.cs
using System;
using System.Collections.Generic;
using System.Text;


namespace DonorCentar.Models
{
    public class Primalac
    {
        public int Id { get; set; }
        public Korisnik Korisnik { get; set; }
        public int KorisnikId { get; set; }
        public DateTime DatumRegistracije { get; set; }
        public bool Verifikovan { get; set; }
    }
}

DonorCentar/DonorCentar/ViewModels/PregledDonacijaViewModel.cs
using DonorCentar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;
using X.PagedList.Mvc;


namespace DonorCentar.ViewModels
{
    public class PregledDonacijaViewModel
    {
        public Donacija Donacija { get; set; }
        public int ObavijestiId { get; set; }
    }
}

DonorCentar/DonorCentar/Controllers/PrimalacController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using DonorCentar.Helper;
using DonorCentar.Hubs;
using DonorCentar.Models;
using DonorCentar.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace DonorCentar.Controllers
{
    public class PrimalacController : Controller
    {
        private BazaPodataka db;
        private IHubContext<NotificationHub> _hubContext;

        public PrimalacController(IHubContext<NotificationHub> hubContext, BazaPodataka _db)
        {
            _hubContext = hubContext;
            db = _db;
        }

        public IActionResult Index()
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 2)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            int primalacId = db.Primalac.Where(p => p.KorisnikId == k.Id).FirstOrDefault().Id;
            bool verifikovan = db.Primalac.Where(p => p.KorisnikId == k.Id).FirstOrDefault().Verifikovan;

            var korisnikViewModel = new KorisnikVM
            {
                Id = primalacId,
                Naziv = k.LicniPodaci.Naziv,
                TipKorisnika = k.TipKorisnika.Tip,
                Adresa = k.LicniPodaci.Adresa,
                BrojTelefona = k.LicniPodaci.BrojTelefona,
                Email = k.LicniPodaci.Email,
                Grad = k.Grad.Naziv,
                Verifikovan = verifikovan,
                PozitivniDojmovi = db.DojamKorisnik.Where(d => d.KorisnikId == k.Id).Count(d => d.DojamId == 1),
                NeutralniDojmovi = db.DojamKorisnik.Where(d => d.KorisnikId == k.Id).Count(d => d.DojamId == 2),
                NegativniDojmovi = db.DojamKorisnik.Where(d => d.KorisnikId == k.Id).Count(d => d.DojamId == 3)
            };

            PostaviViewBag(k.Id, "Index");
            return View(korisnikViewModel);
        }

        public ActionResult Obavijesti()
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 2)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            ObavijestiVM model = new ObavijestiVM
            {
                rows = db.Obavijest.Where(d => d.ZaKorisnikId == k.Id).Select(o => new ObavijestiVM.Row
                {
                    ZaKorisnikId = o.ZaKorisnikId,
                    ObavijestId = o.ObavijestId,
                    Naziv = o.OdKorisnik.LicniPodaci.Naziv,
                    Obavijest = o.TipObavijesti.Obavijest,
                    Vrijeme = o.Vrijeme,
                    OdKorisnikId = o.OdKorisnikId,
                    TipKorisnikaId = o.TipKorisnikaId,
                    TipObavijestiId = o.TipObavijestiId
                }).ToList()
            };

            PostaviViewBag(k.Id, "Obavijesti");
            return View(model);
        }

        public ActionResult DodajPotrebu()
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 2)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            var viewModel = new DodajDonacijuPotrebuViewModel
            {
                TipDonacije = db.TipDonacije.Select(t => new SelectListItem { Value = t.TipDonacijeId.ToString(), Text = t.Tip }).ToList(),
            };

            PostaviViewBag(k.Id, "DodajPotrebu");
            return View(viewModel);
        }

        public ActionResult Uredi(int donacijaId)
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 2)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            Donacija donacija = db.Donacija.Find(donacijaId);

            DodajDonacijuPotrebuViewModel viewModel = new DodajDonacijuPotrebuViewModel
            {
                TipDonacije = db.TipDonacije.Select(t => new SelectListItem { Value = t.TipDonacijeId.ToString(), Text = t.Tip }).ToList(),
                DonacijaId = donacija.DonacijaId,
                JedinicaMjere = (JedinicaMjere)donacija.JedinicaMjere,
                Kolicina = (int)donacija.Kolicina,
                Opis = donacija.Opis,
                TipDonacijeId = donacija.TipDonacijeId
            };

            PostaviViewBag(k.Id, "MojePotrebe");
            return View("DodajPotrebu", viewModel);
        }

        public ActionResult IzbrisiObavijest(int obavijestId)
        {
            Obavijest o = db.Obavijest.Find(obavijestId);
            db.Obavijest.Remove(o);
            db.SaveChanges();

            return RedirectToAction("Obavijesti");
        }

        public ActionResult IzbrisiPotrebu(int donacijaId, int? page2)
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 2)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            Donacija d = db.Donacija.Find(donacijaId);
            db.Donacija.Remove(d);
            db.SaveChanges();

            IEnumerable<Donacija> donacija = db.Donacija.Where(s => s.DonorId == null)
                .Where(s => s.PrimalacId == k.Id)
                .Where(s => s.VrstaDonacijeId == 2)
                .Include(s => s.Status)
                .Include(s => s.TipDonacije)
                .ToList();

            ViewBag.Prikazi = "prikazi";
            PostaviViewBag(k.Id, "MojePotrebe");
            return View("MojePotrebe", donacija.ToPagedList(page2 ?? 1, 5));
        }

        public ActionResult SpasiPotrebu(DodajDonacijuPotrebuViewModel viewModel)
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 2)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            Donacija d = new Donacija
            {
                JedinicaMjere = (JedinicaMjere)viewModel.JedinicaMjere,
                Kolicina = (int)viewModel.Kolicina,
                Opis = viewModel.Opis,
                PrimalacId = k.Id,
                StatusId = 2,
                TipDonacijeId = viewModel.TipDonacijeId,
                VrstaDonacijeId = 2
            };

            if (viewModel.DonacijaId == 0)
            {
                db.Donacija.Add(d);
            }
            else
            {
                var objectDb = db.Donacija.Find(viewModel.DonacijaId);
                objectDb.JedinicaMjere = (JedinicaMjere)viewModel.JedinicaMjere;
                objectDb.Kolicina = (int)viewModel.Kolicina;
                objectDb.Opis = viewModel.Opis;
                objectDb.TipDonacijeId = viewModel.TipDonacijeId;
            }

            db.SaveChanges();
            
            ViewBag.Prikazi = "prikazi";
            return RedirectToAction("MojePotrebe");
        }

        public ActionResult MojePotrebe(int? page)
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 2)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            IEnumerable<Donacija> donacija = db.Donacija.Where(s => s.DonorId == null).Where(s => s.PrimalacId == k.Id).Where(s => s.VrstaDonacijeId == 2).Include(s => s.Status).Include(s => s.TipDonacije).ToList();

            PostaviViewBag(k.Id, "MojePotrebe");
            return View(donacija.ToPagedList(page ?? 1, 5));
        }

        public ActionResult PregledDonacija(int? page)
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 2)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            IEnumerable<Donacija> donacija = db.Donacija.Where(s => s.StatusId == 1)
                .Where(s => s.VrstaDonacijeId == 1).Include(s => s.Status).Include(s => s.TipDonacije).
                Include(s => s.Donor.LicniPodaci).ToList();

            PostaviViewBag(k.Id, "PregledDonacija");
            return View(donacija.ToPagedList(page ?? 1, 4));
        }

        public ActionResult ZatrazeneDonacije(int? page)
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 2)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            IEnumerable<Donacija> donacija = db.Donacija.Where(s => s.StatusId == 6 || s.StatusId == 4 || s.StatusId == 3)
            .Where(s => s.PrimalacId == k.Id)
            .Include(s => s.Status).Include(s => s.TipDonacije)
            .Include(s => s.Donor)
            .Include(s => s.Donor.LicniPodaci).ToList();

            PostaviViewBag(k.Id, "ZatrazeneDonacije");
            return View(donacija.ToPagedList(page ?? 1, 5));
        }

        public ActionResult DetaljiDonacije(int donacijaId, int akcija)
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            if (k == null || k.TipKorisnikaId != 2)
            {
                ViewData["error_poruka"] = "Nemate pravo pristupa.";
                return View("../Home/Index");
            }

            PrimalacDetaljiDonacijeVM model = db.Donacija.Where(d => d.DonacijaId == donacijaId)
                .Select(d => new PrimalacDetaljiDonacijeVM
            {

DonorCentar/DonorCentar/Views/Primalac/DetaljiDonacije.cshtml
@model DonorCentar.ViewModels.PrimalacDetaljiDonacijeVM

@{
    ViewData["Title"] = "DetaljiDonacije";
    Layout = "~/Views/Shared/_Primalac.cshtml";
}

<div class="content-box">
    <form id="DetaljiDonacije">
        <div id="pregled-donacije-split">
            <div id="pregled-donacije-left">
                <div class="form-group">
                    <h3 class="text-muted">Donor</h3>
                    <input type="text" readonly class="form-control" asp-for="DonorNaziv" />
                </div>
                <div class="form-group">
                    <h3 class="text-muted">Adresa</h3>
                    <input type="text" readonly class="form-control" value="@Model.DonorAdresa, @Model.DonorGrad" />
                </div>
                <div class="form-group">
                    <h3 class="text-muted">Tip donacije</h3>
                    <input type="text" readonly class="form-control" value="@Model.TipDonacije" />
                </div>
            </div>
            <div id="pregled-donacije-right">
                <div class="form-group">
                    <h3 class="text-muted">Opis</h3>
                    <textarea readonly class="form-control bigger-box">@Model.Opis</textarea>
                </div>
                <div class="form-group">
                    <h3 class="text-muted">Količina</h3>
                    <input type="text" readonly value="@Model.Kolicina @Model.JedinicaMjere" class="form-control" />
                </div>
                <div class="form-group">
                    <h3 class="text-muted">Transport</h3>
                    @{
                        if (Model.TransportId != 0 && Model.InformacijeId == 1)
                        {
                            <input type="text" readonly class="form-control" value="@Model.DonorNaziv obezbjeđuje transport" />
                        }
                        else if (Model.InformacijeId == 2)
                        {
                            <input type="text" readonly class="form-control" value="@Model.DonorNaziv transport na nivou kantona" />
                        }
                        else if (Model.InformacijeId == 3)
                        {
                            <input type="text" readonly class="form-control" value="@Model.DonorNaziv obezbjeđuje transport na nivou grada" />
                        }
                        else
                        {
                            <input type="text" readonly class="form-control" value="Transport nije obezbjeđen" />
                        }
                    }
                </div>


                <input type="hidden" asp-for="DonacijaId" />
            </div>
        </div>
        @if (ViewBag.akcija == 1)
        {
            <a class="btn btn-dark" asp-action="ZatrazeneDonacije">Nazad</a>
        }
        else
        {
            <a class="btn btn-dark" asp-action="PregledDonacija">Nazad</a>
        }
    </form>
</div>

DonorCentar/DonorCentar/Views/Primalac/DodajPotrebu.cshtml
@model DonorCentar.ViewModels.DodajDonacijuPotrebuViewModel

@{
    ViewData["Title"] = "DodajPotrebu";
    Layout = "~/Views/Shared/_Primalac.cshtml";
}


    <div class="content-box">
        <form asp-action="SpasiPotrebu">
            <div class="form-group">
                <label for="TipDonacijeId">Tip donacije</label>
                <select id="TipDonacijeId" asp-for="TipDonacijeId" asp-items="Model.TipDonacije" class="form-control">
                    <option value="">Izaberite tip donacije</option>
                </select>
                <span asp-validation-for="TipDonacijeId"></span>
            </div>
            <div class="form-group">
                <label for="Opis">Opis</label>
                <textarea id="Opis" asp-for="Opis" class="form-control bigger-box"></textarea>
                <span asp-validation-for="Opis"></span>
            </div>
            <div class="form-group">
                <label for="Kolicina">Kolicina</label>
                <input id="Kolicina" type="text" asp-for="Kolicina" class="form-control" />
                <span asp-validation-for="Kolicina"></span>
            </div>
            <div class="form-group JedinicaM">
                <label for="JedinicaMjere">Jedinica mjere</label>
                <select id="JedinicaMjere" asp-for="JedinicaMjere" asp-items="Html.GetEnumSelectList<JedinicaMjere>()" class="form-control">
                    <option value="">Izaberite jedinicu mjere</option>
                </select>
                <span asp-validation-for="JedinicaMjere"></span>
            </div>

            <input type="hidden" asp-for="DonacijaId" />
            <button type="submit" class="btn btn-dark">Spasi</button>
        </form>



        <div class="modal" tabindex="-1" role="dialog" id="myModal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Potreba spašena</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>Potreba je uspješno spašena.</p>
                    </div>
                    <div class="modal-footer">
                        <a asp-action="DodajPotrebu" class="btn btn-primary">U redu</a>
                    </div>
                </div>
            </div>
        </div>
    </div>



@section Scripts {
    <script>
        if ('@ViewBag.Prikazi' != null && '@ViewBag.Prikazi' == "prikazi")
        {
            $('#myModal').modal('show');
        }
    </script>
}

DonorCentar/DonorCentar/Views/Primalac/DonacijaJeStigla.cshtml
@model DonorCentar.ViewModels.PrimalacDonacijaJeStiglaVM

@{
    ViewData["Title"] = "DonacijaJeStigla";
    Layout = "~/Views/Shared/_Primalac.cshtml";
}


    <div class="content-box">
        <form asp-action="DodajDojam">
            <div class="form-group">
                <label for="DojamId">Dojam</label>
                <select id="DojamId" asp-for="DojamId" asp-items="Model.ListaDojmova" class="form-control">
                    <option value="">Izaberite dojam</option>
                </select>
                <span asp-validation-for="DojamId"></span>
            </div>
            <div class="form-group">
                <label for="Opis">Opis</label>
                <textarea id="Opis" asp-for="Opis" class="form-control bigger-box"></textarea>
                <span asp-validation-for="Opis"></span>
            </div>

            <input asp-for="DonacijaId" type="hidden" />
            <input asp-for="KorisnikId" type="hidden" />

            <button class="btn btn-primary" type="submit">Spasi</button>
        </form>
    </div>

DonorCentar/DonorCentar/Views/Primalac/HistorijaDonacija.cshtml
@{
    ViewData["Title"] = "HistorijaDonacija";
    Layout = "~/Views/Shared/_Primalac.cshtml";
}

<h1>HistorijaDonacija</h1>

DonorCentar/DonorCentar/Views/Primalac/Index.cshtml
@model DonorCentar.ViewModels.KorisnikVM;

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Primalac.cshtml";
}
<div class="content-box">

    <div id="profil">
        @await Html.PartialAsync("_Profil")
    </div>
</div>

DonorCentar/DonorCentar/Views/Primalac/MojePotrebe.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Core;

@model IPagedList<DonorCentar.Models.Donacija>
@{
    ViewData["Title"] = "MojePotrebe";
    Layout = "~/Views/Shared/_Primalac.cshtml";
}


<div class="content-box">
    <div class="page-box">
        <table class="table table-hover">
            <thead>
                <tr class="table-primary">
                    <th>Tip donacije</th>
                    <th>Količina</th>
                    <th>Jedinica mjere</th>
                    <th>Status</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var x in Model)
                {
                <tr>
                    <td>@x.TipDonacije.Tip</td>
                    <td>@x.Kolicina</td>
                    <td>@x.JedinicaMjere</td>
                    <td>@x.Status.Opis</td>
                    @if (x.StatusId == 2)
                    {
                        <td><a class="btn btn-success" asp-action="Uredi" asp-route-donacijaId="@x.DonacijaId">Uredi</a></td>
                        <td><a class="btn btn-danger" asp-action="IzbrisiPotrebu" asp-route-donacijaId="@x.DonacijaId">Izbriši</a></td>
                    }
                    else
                    {
                        <td></td>
                        <td></td>
                    }
                </tr>
                }
            </tbody>
        </table>
        @Html.PagedListPager(Model, page => Url.Action("MojePotrebe", new { page }))
    </div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="izbrisiModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Potreba dodana</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Potreba je uspješno izbrisana.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">U redu</button>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    <script>
        if ('@ViewBag.Prikazi' != null && '@ViewBag.Prikazi' == "prikazi")
        {
            $('#izbrisiModal').modal('show');
        }
    </script>
}

DonorCentar/DonorCentar/Views/Primalac/OstaliKorisnici.cshtml
@{
    ViewData["Title"] = "OstaliKorisnici";
    Layout = "~/Views/Shared/_Primalac.cshtml";
}

<h1>OstaliKorisnici</h1>

DonorCentar/DonorCentar/Views/Primalac/PregledDonacija.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Core;

@model IPagedList<DonorCentar.Models.Donacija>

@{
    ViewData["Title"] = "PregledDonacija";
    Layout = "~/Views/Shared/_Primalac.cshtml";

    string naslov = "";
    string poruka = "";
    if (ViewBag.Prikazi == "Zatrazeno")
    {
        naslov = "Donacija zatražena";
        poruka = "Zahtjev za donacijom je uspješno poslan. Čekajte na odgovor.";
    }
}

<div class="content-box">
    <div class="page-box">
        <table class="table table-dark">
            <thead>
                <tr>
                    <th>Naziv donora</th>
                    <th>Tip donacije</th>
                    <th>Količina</th>
                    <th>Jedinica mjere</th>
                    <th>Status</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var x in Model)
                {
                    <tr>
                        <td>@x.Donor.LicniPodaci.Naziv</td>
                        <td>@x.TipDonacije.Tip</td>
                        <td>@x.Kolicina</td>
                        <td>@x.JedinicaMjere</td>
                        <td>@x.Status.Opis</td>
                        <td><a class="btn btn-info" asp-action="DetaljiDonacije" asp-controller="Primalac" asp-route-donacijaId="@x.DonacijaId"
                               asp-route-akcija="2">Detalji donacije</a></td>
                        <td>
                            <a class="btn btn-success" asp-action="ZatraziDonaciju" asp-route-donacijaId="@x.DonacijaId">Zatraži donaciju</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        @Html.PagedListPager(Model, page => Url.Action("PregledDonacija", new { page }))
    </div>
</div>



<div class="modal" tabindex="-1" role="dialog" id="myModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">

                <h5 class="modal-title">@naslov</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>@poruka</p>
            </div>
            <div class="modal-footer">
                <a asp-action="PregledDonacija" class="btn btn-primary">U redu</a>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script>
        if ('@ViewBag.Prikazi' != null && ('@ViewBag.Prikazi' == "Ponisteno" || '@ViewBag.Prikazi' == "Zatrazeno"))
        {
            $('#myModal').modal('show');
        }
    </script>
}

DonorCentar/DonorCentar/Views/Primalac/ZatrazeneDonacije.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Core;

@model IPagedList<DonorCentar.Models.Donacija>

@{
    ViewData["Title"] = "Zatrazene donacije";
    Layout = "~/Views/Shared/_Primalac.cshtml";

    string naslov, poruka;
    if (ViewBag.Prikazi == "Zatrazeno")
    {
        naslov = "Donacija zatražena";
        poruka = "Zahtjev za donacijom je uspješno poslan. Čekajte na odgovor.";
    }
    else if (ViewBag.Prikazi == "Transport")
    { 
        naslov = "Transport omogućen";
        poruka = "Od sada ste vi zaduženi za transport.";
    }
    else 
    { 
        naslov = "Zahtjev poništen";
        poruka = "Zahtjev za donacijom je poništen.";
    }
}

<div class="content-box">
    <div class="page-box">
        <table class="table table-dark">
            <thead>
                <tr>
                    <th>Naziv donora</th>
                    <th>Tip donacije</th>
                    <th>Količina</th>
                    <th>Jedinica mjere</th>
                    <th>Status</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
               @foreach (var x in Model)
                {
                <tr>
                    <td>@x.Donor.LicniPodaci.Naziv</td>
                    <td>@x.TipDonacije.Tip</td>
                    <td>@x.Kolicina</td>
                    <td>@x.JedinicaMjere</td>
                    <td>@x.Status.Opis</td>
                    <td><a class="btn btn-info" asp-action="DetaljiDonacije" asp-controller="Primalac" 
                           asp-route-donacijaId="@x.DonacijaId"
                           asp-route-akcija="1">Detalji donacije</a></td>
                   @if (x.StatusId == 3)
                    {
                        <!-- Bez transporta -->
                        <td>
                            <a class="btn btn-success" asp-action="ObezbjediTransport" asp-route-donacijaId="@x.DonacijaId">Obezbjedi transport</a>
                        </td>
                    }
                    else if (x.StatusId == 4)
                    {
                        <!-- U fazi transporta -->
                        <td>
                            <a class="btn btn-success" asp-action="DonacijaJeStigla" asp-route-donacijaId="@x.DonacijaId">Donacija je stigla</a>
                        </td>
                    }
                    else
                    {
                        <!-- StatusId = 6 Zatrazena -->
                        <td>
                             <a class="btn btn-danger" asp-action="PonistiZahtjev" asp-route-donacijaId="@x.DonacijaId">Poništi zahtjev</a>
                        </td>
                    }
                </tr>
                }
            </tbody>
        </table>
        @Html.PagedListPager(Model, page => Url.Action("MojePotrebe", new { page }))
    </div>
</div>



<div class="modal" tabindex="-1" role="dialog" id="myModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">

                <h5 class="modal-title">@naslov</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>@poruka</p>
            </div>
            <div class="modal-footer">
                <a asp-action="ZatrazeneDonacije" class="btn btn-primary">U redu</a>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script>
        if ('@ViewBag.Prikazi' != null && ('@ViewBag.Prikazi' == "Ponisteno" || '@ViewBag.Prikazi' == "Zatrazeno" || '@ViewBag.Prikazi' == "Transport" ))
        {
            $('#myModal').modal('show');
        }
    </script>
}